version: '3.8'

services:
  webapi:
    build: .  # Usa il Dockerfile nella directory corrente
    container_name: wasatext-backend
    ports:
      # Mappa la porta 8080 del container sulla porta 8080 del tuo host
      - "3000:3000" 
    volumes:
      # Permette di salvare i dati del database (wasa.db) in modo persistente
      # Se il volume non esiste, verrà creato.
      - wasa-data:/app
    # Imposta le variabili d'ambiente necessarie all'app Go (es. l'indirizzo del DB)
    environment:
      - DB_PATH=/app/wasa.db
      # Altre variabili necessarie, come l'indirizzo di ascolto (es. :8080)
      - WEB_API_HOST=:3000
      
volumes:
  wasa-data:  # Definisce il volume persistente